# Generated by Django 3.0.4 on 2020-03-17 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actuator_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_number', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='reading',
            options={'ordering': ['reading_date']},
        ),
        migrations.RemoveField(
            model_name='reading',
            name='parameter_id',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='quantity',
        ),
        migrations.AddField(
            model_name='reading',
            name='reading_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date readed'),
        ),
        migrations.AlterField(
            model_name='log',
            name='log_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date loged'),
        ),
        migrations.DeleteModel(
            name='Parameter',
        ),
        migrations.AddField(
            model_name='value',
            name='reading_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actuator_api.Reading'),
        ),
        migrations.AddField(
            model_name='value',
            name='register_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actuator_api.Register'),
        ),
    ]
