# Generated by Django 3.0.4 on 2020-04-24 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actuator_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'SuperAdmin'), (1, 'Admin'), (2, 'Regular')], null=True),
        ),
    ]
