# Generated by Django 3.0.4 on 2020-05-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actuator_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='unit',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
