# Generated by Django 3.0.4 on 2020-03-22 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actuator_api', '0002_auto_20200317_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='bit_number',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='actuator',
            name='modbus_address',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='log',
            name='actuator_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='actuator_api.Actuator'),
        ),
        migrations.AlterField(
            model_name='log',
            name='event',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='log',
            name='log_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='reading_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='register_number',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, 'SuperAdmin'), (1, 'Admin'), (2, 'Regular')], default=2),
        ),
    ]
