# Generated by Django 3.0.4 on 2020-05-14 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actuator_api', '0003_auto_20200509_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='value',
            name='alert_seen',
            field=models.BooleanField(default=False),
        ),
    ]
