# Generated by Django 3.0.4 on 2020-03-28 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actuator_api', '0003_auto_20200322_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='raw_data',
            field=models.CharField(default='error', max_length=200),
        ),
        migrations.AddField(
            model_name='reading',
            name='response_ok',
            field=models.BooleanField(default=False),
        ),
    ]
