# Generated by Django 3.0.4 on 2020-05-22 22:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actuator_api', '0004_value_alert_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='idn',
            field=models.PositiveIntegerField(default=1, unique=True, validators=[django.core.validators.MaxValueValidator(150000000), django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
