# Generated by Django 3.0.4 on 2020-03-29 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actuator_api', '0004_auto_20200327_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actuator',
            name='modbus_address',
            field=models.SmallIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='actuator',
            name='model',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='actuator',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Active'), (1, 'Inactive')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
