# Generated by Django 3.0.4 on 2020-03-31 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actuator_api', '0005_auto_20200328_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='actuator',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='actuator',
            name='model',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
