# Generated by Django 3.0.4 on 2020-04-03 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actuator_api', '0007_auto_20200402_2215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='actuator_id',
            new_name='actuator',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='reading',
            old_name='actuator_id',
            new_name='actuator',
        ),
        migrations.RenameField(
            model_name='value',
            old_name='reading_id',
            new_name='reading',
        ),
        migrations.RenameField(
            model_name='value',
            old_name='register_id',
            new_name='register',
        ),
    ]
