# Generated by Django 3.0.7 on 2021-09-25 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actuator_api', '0010_auto_20210418_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='diagnosis_ok',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='event',
            field=models.SmallIntegerField(choices=[(0, 'El usuario ha iniciado sesión'), (1, 'El usuario ha cerrado sesión'), (2, 'Se ha creado un nuevo usuario'), (3, 'Un actuador ha sido operado manualmente'), (4, 'Nueva lectura disponible'), (5, 'El usuario accedió a las lecturas del actuador'), (6, 'El actuador se encuentra desconectado')]),
        ),
    ]
